### ISSUE TITLE
Algunas dudas sobre el modelo

### ISSUE THREAD

**Issue by JJ** [cjgb/covid_madrid#1]
Hola,
Me vas a perdonar porque no he usado Stan (ni, para el caso, inferencia bayesiana) nunca, así que te agradecería que me resolvieras unas dudas (o simplemente apúntame a un tutorial que pueda mirar).

* `dia0`, ¿dónde lo usas? ¿O es simplemente una terminología que usa Stan para el primer valor
* modelas `letalidad` como una normal, lo que yo entiendo que significa que generas un valor con esa distribución, ¿no?
* ¿Por qué evoluciona r0?
* ¿Por qué usas el valor de 22 días y no lo modelas con una distribución?

En fin, si tienes un momento, te lo agradecería...

**Comment by cjgb** [comment]
Buenas preguntas.

Veo que `dia0` ha quedado en el segundo modelo como un apéndice no usado del primero que tenía que haber borrado. Era el parámetro que contenía el primer día con datos. En el primer modelo extendía para atrás el tiempo para imputar contagios a días anteriores la primer día de datos y luego usaba los días del `dia0` en lo sucesivo para modelar. En dicho modelo solo se usaba en el `for` (desde `dia0` hasta `N`).

Sí, `letalidad` es un parámetro desconocido cuya incertidumbre asumo normal alrededor de un determinado valor. Podría haber usado una beta para mantenerla entre 0 y 1, pero tiene más parámetros. Lo que enseña el modelo es que esa `letalidad` depende críticamente del número de expuestos y este del tamaño de la _ventana_. La ventana es el rango de días durante los cuales muere la gente una vez contagiada. Creo que he usado desde el día 6 al 22 basado en cosas que he leído por ahí. Pero es algo cuestionable y mejorable.

`r0`, con un abuso de notación, es el número de contagios que produce cada enfermo al día. Evoluciona en el tiempo porque el número de contagios ha evolucionado en el tiempo según las medidas que se han ido adoptando. Parte del interés del modelo es estudiar esa evolución para medir la eficacia de las medidas de distanciamiento socia, etc., tomadas.

Y uso 22 días en lugar de una distribución porque si quiero ajustar una distribución, creo un montón de grados de libertad adicionales y no tengo más datos que los que hay. Tomé 22, ya digo, inspirado en cosas que leí. Luego extendí la ventana. Y sí, el modelo es muy sensible a esos parámetros. Si el modelo se extendiese a otras zonas habría más datos y se podría, indirectamente, tratar de estimar mejor la _ventana de letalidad_.

**Comment by JJ** [comment]
¡Muchísimas gracias!
